name: meditate

on:
  push:
  # schedule:
  #   - cron: '0 1-9 * * *' # pro-tip: https://crontab.guru
  workflow_dispatch:
    inputs:
      prompt:
        description: Please provide a prompt for completion.
        required: true

jobs:
  meditate:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - run: npm install

      - name: meditation
        id: meditation
        run: npm start

      - uses: actions/checkout@v2
      - name: tick
        run: |
          echo -e ${{ steps.meditation.outputs.response }} > README.md
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git config --global user.name "${GITHUB_ACTOR}"
          git add README.md
          git commit -m "meditate" -m "${{ steps.meditation.outputs.prompt }}"
          git push origin main
